# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(419, 305)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.oznitelik_sayisi = QtWidgets.QLineEdit(self.centralwidget)
        self.oznitelik_sayisi.setObjectName("oznitelik_sayisi")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.oznitelik_sayisi)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.veri_sayisi = QtWidgets.QLineEdit(self.centralwidget)
        self.veri_sayisi.setObjectName("veri_sayisi")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.veri_sayisi)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.normalizasyon_z_score = QtWidgets.QRadioButton(self.centralwidget)
        self.normalizasyon_z_score.setObjectName("normalizasyon_z_score")
        self.horizontalLayout_2.addWidget(self.normalizasyon_z_score)
        self.normalizasyon_minmax = QtWidgets.QRadioButton(self.centralwidget)
        self.normalizasyon_minmax.setObjectName("normalizasyon_minmax")
        self.horizontalLayout_2.addWidget(self.normalizasyon_minmax)
        self.normalizasyon_yok = QtWidgets.QRadioButton(self.centralwidget)
        self.normalizasyon_yok.setChecked(True)
        self.normalizasyon_yok.setObjectName("normalizasyon_yok")
        self.horizontalLayout_2.addWidget(self.normalizasyon_yok)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.korelasyon_katsayisi = QtWidgets.QLineEdit(self.centralwidget)
        self.korelasyon_katsayisi.setObjectName("korelasyon_katsayisi")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.korelasyon_katsayisi)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.ilerle_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ilerle_btn.setObjectName("ilerle_btn")
        self.verticalLayout.addWidget(self.ilerle_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 419, 26))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.veriseti_goruntule_action = QtWidgets.QAction(MainWindow)
        self.veriseti_goruntule_action.setObjectName("veriseti_goruntule_action")
        self.menuDosya.addAction(self.veriseti_goruntule_action)
        self.menubar.addAction(self.menuDosya.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sentetik Veri Üretici"))
        self.label.setText(_translate("MainWindow", "Sentetik Veri Üretici"))
        self.label_2.setText(_translate("MainWindow", "Öznitelik Sayısı : "))
        self.label_4.setText(_translate("MainWindow", "Veri Sayısı :"))
        self.label_3.setText(_translate("MainWindow", "Korelasyon Katsayısı : "))
        self.label_5.setText(_translate("MainWindow", "Normalizasyon : "))
        self.normalizasyon_z_score.setText(_translate("MainWindow", "Z-Score"))
        self.normalizasyon_minmax.setText(_translate("MainWindow", "Min-Max"))
        self.normalizasyon_yok.setText(_translate("MainWindow", "Yok"))
        self.ilerle_btn.setText(_translate("MainWindow", "İlerle"))
        self.menuDosya.setTitle(_translate("MainWindow", "Dosya"))
        self.veriseti_goruntule_action.setText(_translate("MainWindow", "Veriseti görüntüle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

